add: Blunt Execution Rounds
d2foundry/oracle_engine pull request #113
Opened 2024-05-04 14:07 UTC by FlaminSarge

2024-05-04 14:08 UTC, FlaminSarge commented on src/perks/year_4_perks.rs
> +                || _input.calc_data.total_shots_fired > _input.calc_data.curr_firing_data.burst_size.into()
Unclear if total_shots_fired is the right field to use for this check (vs shots_fired_in_mag or other) given that you can re-proc BXR after a 4 second cooldown after using it.

2024-05-05 08:39 UTC, FlaminSarge commented on src/perks/year_4_perks.rs
> +                || _input.calc_data.total_shots_fired > _input.calc_data.curr_firing_data.burst_size.into()
> [6:24 PM]andromeda: just use total shots fired

2024-05-14 22:01 UTC, BarmonHammer requested changes

2024-05-14 22:01 UTC, BarmonHammer commented on src/perks/year_4_perks.rs
> +                0
guard

2024-05-15 00:22 UTC, BarmonHammer approved these changes

2024-05-15 00:22 UTC, merged