add: Lucent Blades
d2foundry/oracle_engine pull request #72
Opened 2023-10-14 23:46 UTC by Pixeled99

https://discord.com/channels/1044304864903168061/1159055987207053342

2023-10-14 23:54 UTC, Pixeled99 commented
Sorry about that! Should have tried building it before

2023-10-15 00:05 UTC, BarmonHammer requested changes

2023-10-15 00:05 UTC, BarmonHammer commented on src/perks/buff_perks.rs
> +            }
You should probably use a match statement instead?
Something like this:
```rust
let stat_bump = match value {
0 => return HashMap::default(),
1 => 30,
2 => 50,
3.. => 60,
}
HashMap::from([(StatHashes::CHARGE_RATE.into(), stat_bump)])
```

2023-10-15 00:05 UTC, BarmonHammer commented on src/perks/buff_perks.rs
> +        Box::new(|_input: ModifierResponseInput| -> HashMap<u32, i32> {
I would add a guard conditional that makes sure the weapon type is a Sword

2023-10-15 00:18 UTC, Pixeled99 commented on src/perks/buff_perks.rs
> +            }
I had a match statement in the first commit but it wasn't compiling so I switched to if statements

2023-10-15 00:19 UTC, Pixeled99 commented on src/perks/buff_perks.rs
> +        Box::new(|_input: ModifierResponseInput| -> HashMap<u32, i32> {
How can I do that?

2023-10-15 00:24 UTC, BarmonHammer commented on src/perks/buff_perks.rs
> +            }
It's because your match arms had incompatible types, the above example should work fine.

2023-10-15 00:26 UTC, BarmonHammer commented on src/perks/buff_perks.rs
> +        Box::new(|_input: ModifierResponseInput| -> HashMap<u32, i32> {
Something like 
```rust
if _input.calc_data.weapon_type != &WeaponType::SWORD {
       return HashMap::new()
}
```

2023-10-16 21:07 UTC, BarmonHammer approved these changes

2023-10-16 21:08 UTC, merged